# for shared configurations between environments
# https://hub.docker.com/_/mongo
version: "3"
services:
  my-web-container:
    build: .
    ports:
      - "3000:4000"
    env_file:
      - ./.env
    depends_on: # start mongo before starting the web container because web container depends on mongo
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-data:/data/db # named volume to persist data, /data/db is the default data directory for mongo acc to docs
    env_file:
      - ./.env

volumes:
  mongo-db-data:
