# for development environment
version: "3"
services:
  my-web-container:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app # bind volume to mount current directory to /app
      - /app/node_modules #  anon volume to exclude node_modules from being mounted
    environment:
      - NODE_ENV=development
    command: npm run dev
